name: Python Unit Tests

on:
  push:
    branches:
      - dev-build

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PT_TESTING_MODE: True
      PT_SECRET_KEY: "github-actions-key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: |
          python -m coverage run -m unittest discover
          python -m coverage html
          python -m coverage report > coverage.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov

      - name: Display coverage report
        run: cat coverage.txt
